### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower' on sponsor_info

### ISSUE THREAD

**Issue by ferrarimarco** [github/contributors#52]
We got this error in the super-linter repo (https://github.com/super-linter/super-linter/actions/runs/6714831338/job/18248627198)

```python
Traceback (most recent call last):
  File "/action/workspace/contributors.py", line 174, in <module>
    main()
  File "/action/workspace/contributors.py", line 23, in main
    ) = env.get_env_vars()
        ^^^^^^^^^^^^^^^^^^
  File "/action/workspace/env.py", line 56, in get_env_vars
    sponsor_info = sponsor_info.lower().strip()
                   ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

@zkoppert can you kindly have a look? Thanks!

**Comment by zkoppert** [comment]
Released! https://github.com/github/contributors/releases/tag/v1.1.2

**Comment by zkoppert** [comment]
Reran the workflow on the super-linter side and failed at a new spot. Fixing that now: https://github.com/github/contributors/pull/54

**Comment by ferrarimarco** [comment]
Nice work!
